### ISSUE TITLE
Debian installation

### ISSUE THREAD

**Issue by amichaut** [AlexandreCampo/useTracker#1]
Hi, 
Is the stable version (downloaded from the website) installation only for ubuntu or is it supposed to be working also on debian distributions?
Because the installation is bugged on my debian machine. 
Thanks for your help, 
Arthur

**Comment by AlexandreCampo** [comment]
Hi Arthur, 
Thanks for reporting the problem, it was due to Debian not using sudo. 
I just committed a fix that should work for you (tested in debian 8). Let me know if this works for you.
Cheers, Alex.

**Comment by amichaut** [comment]
Yes it works fine now! Thanks!

2015-04-30 19:52 GMT+02:00 Alexandre Campo notifications@github.com:

**Comment by AlexandreCampo** [comment]
You're welcome, thanks for testing!
